
## promise all with objects

```typescript
type AwaitedObject<T> = { [K in keyof T]: Awaited<T[K]> };

async function allWithObject<T extends Record<string, any>>(
  promises: T,
): Promise<AwaitedObject<T>> {
  const keys = Object.keys(promises) as (keyof T)[];
  const resultEntries = await Promise.all(
    keys.map(
      async (key) => [key, await promises[key]] as const,
    ),
  );
  return Object.fromEntries(
    resultEntries,
  ) as AwaitedObject<T>;
}

const promiseObject = {
  first: Promise.resolve({ p: 1 }),
  second: Promise.resolve("two"),
  third: Promise.resolve(true),
};
allWithObject(promiseObject)
  .then((results) =>
    console.log("results:", results.first.p),
  )
  .catch((error) => console.error("error:", error));
// results: 1

const promiseObjectWithRejection = {
  first: Promise.resolve(1),
  second: Promise.reject(new Error("Promise rejected")),
  third: Promise.resolve("three"),
};
allWithObject(promiseObjectWithRejection)
  .then((results) => console.log("results:", results))
  .catch((error) => console.error("error:", error.message));
// error: Promise rejected
```